import { ADDRESS_TYPES } from "./address.constants";

export const addressesData = [
  {
    id: "address-1",
    type: ADDRESS_TYPES.HOME,
    label: "Home",
    fullName: "Aman Verma",
    phone: "+91 98765 43210",
    addressLine1: "123, Green Park Street",
    addressLine2: "Sector 21",
    city: "Noida",
    state: "Uttar Pradesh",
    pincode: "201301",
    country: "India",
    isDefault: true,
  },
  {
    id: "address-2",
    type: ADDRESS_TYPES.OFFICE,
    label: "Office",
    fullName: "Aman Verma",
    phone: "+91 98765 43210",
    addressLine1: "456, Tech Park, Tower B",
    addressLine2: "Sector 62",
    city: "Noida",
    state: "Uttar Pradesh",
    pincode: "201309",
    country: "India",
    isDefault: false,
  },
  {
    id: "address-3",
    type: ADDRESS_TYPES.PARENTS_HOME,
    label: "Parents Home",
    fullName: "Aman Verma",
    phone: "+91 98765 43210",
    addressLine1: "Vill. Shahpur, Post Kidiharpur",
    addressLine2: "",
    city: "Ballia",
    state: "Uttar Pradesh",
    pincode: "221716",
    country: "India",
    isDefault: false,
  },
];